<a href="https://colab.research.google.com/github/gk-gokul/image_diffusion/blob/main/Forward_Diffusion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
def forward_diffusion(x0, t, betas = torch.linespace(0.0, 1.0, 5)):
   noise = torch.rand_like(x0)

In [ ]:
x0 = torch.randn(2,3,32,32)

In [ ]:
beta = torch.tensor([0.05,0.1,0.15,0.2,0.25])

In [ ]:
t = torch.tensor([1,3])

In [ ]:
alpha = 1 - beta

In [ ]:
alpha_hat = torch.cumprod(alpha, axis = 0)

In [ ]:
result = alpha_hat.gather(-1,t).reshape(-1,1,1,1)

In [ ]:
alpha_hat

tensor([0.9500, 0.8550, 0.7268, 0.5814, 0.4360])

In [ ]:
result.size()

torch.Size([2, 1, 1, 1])

In [ ]:
x0.size()

torch.Size([2, 3, 32, 32])

In [ ]:
noise =  torch.rand_like(x0)
mean = result.sqrt()*x0
variance = torch.sqrt(1-result)* noise

In [ ]:
x_t = mean + variance

In [ ]:
x_t[0]

tensor([[[-0.7501, -0.4327,  0.8111,  ..., -1.1709, -0.9754,  0.7447],
         [ 0.0168,  1.7746, -0.3924,  ...,  0.9683, -0.6558, -0.2191],
         [-1.3673,  0.8247,  0.4525,  ..., -0.0047,  0.8394, -0.5299],
         ...,
         [ 0.8675, -0.9971, -0.2159,  ..., -1.2275, -0.4421, -0.9354],
         [ 2.2079, -0.0415,  0.3300,  ...,  0.4823,  0.2867,  1.5106],
         [ 0.2828, -0.5361, -0.4743,  ...,  0.6215,  1.1820,  1.2360]],

        [[-0.2948,  0.8588,  0.3481,  ..., -0.0761, -0.6388, -0.4037],
         [-0.7077, -1.2954, -0.6058,  ..., -1.0395,  2.5491,  0.4040],
         [-0.2717,  0.5028,  0.5524,  ...,  0.3078,  1.0684,  1.0616],
         ...,
         [-0.8533,  0.3966, -0.0690,  ...,  0.2923, -1.3552,  1.3536],
         [ 0.8653,  0.6693,  1.6085,  ...,  1.2681, -0.3006,  0.4926],
         [ 0.2551,  0.2868,  1.3123,  ...,  0.8794,  0.5437,  1.0049]],

        [[ 1.0110, -0.5332,  1.6362,  ..., -0.1077,  1.0021, -0.4799],
         [-0.2374, -0.5795,  0.5296,  ...,  0

In [ ]:
x_t[1]

tensor([[[ 0.6157,  0.4935,  0.3128,  ...,  0.3493,  1.3095, -0.2984],
         [ 1.2506,  0.1157,  0.5088,  ...,  1.2120,  0.1799,  0.4016],
         [ 0.7976, -0.9672,  0.9796,  ...,  0.3413,  1.0937,  0.2670],
         ...,
         [-0.4828, -0.6731,  0.4907,  ..., -0.5066, -0.3577,  0.0551],
         [ 0.3028,  0.1174, -0.4407,  ..., -0.4921,  0.8700,  1.7762],
         [-0.4980,  1.1123, -1.6579,  ...,  0.2495,  0.6832,  0.9769]],

        [[-0.2537,  0.4262, -0.6246,  ...,  0.4575, -0.1396,  0.3641],
         [ 0.8738,  1.2436,  0.5828,  ...,  0.6110,  0.1231, -0.8458],
         [ 0.0285, -0.6678,  0.4743,  ...,  1.4201,  1.2040,  1.2898],
         ...,
         [ 0.8001,  0.7790,  1.1402,  ...,  1.1099,  0.8468, -0.7202],
         [ 0.5061,  0.8271, -0.5279,  ...,  0.6390,  0.4845,  0.6057],
         [-0.1165, -0.4044,  2.1762,  ...,  1.3959,  0.0792,  1.1827]],

        [[-0.9067,  0.7061,  1.3423,  ..., -0.1031,  0.9937,  0.5084],
         [ 0.3672, -0.3755, -0.3918,  ...,  0